name: Docker CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        load: true
        tags: flask-app:test
        cache-from: type=gha
        cache-to: type=gha,mode=max
      
    - name: Run tests in Docker container
      run: |
        docker run --rm flask-app:test pytest
        
    - name: Run Docker image
      run: |
        docker run -d -p 5000:5000 --name flask-container flask-app:test

        # Wait for app to become responsive
        for i in {1..10}; do
          if curl -s http://localhost:5000/ > /dev/null; then
            echo "App is up!"
            break
          fi
          echo "Waiting for the app to start..."
          sleep 2
        done
        
    - name: Debug container logs (optional, for troubleshooting)
      run: docker logs flask-container
      
    - name: Test the running application
      run: |
        response=$(curl -s http://localhost:5000/)
        echo "Application response: $response"
        if [[ "$response" != "Hello, Docker CI World!" ]]; then
          echo "Unexpected response from application"
          exit 1
        fi
        
        health_response=$(curl -s http://localhost:5000/health)
        echo "Health endpoint response: $health_response"
        if [[ "$health_response" != *"healthy"* ]]; then
          echo "Health check failed"
          exit 1
        fi
        
    - name: Clean up
      run: |
        docker stop flask-container || true
        docker rm flask-container || true

    - name: Clean up
      run: |
        docker stop flask-container || true
        docker rm flask-container || true
